version: "3.8"
services:
  app:
    container_name: M1P10AndroidNode
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - 50400:3000
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tourisme
      MYSQL_USER: tourismeUser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:

